package org.hdf5javalib.dataclass;

import org.hdf5javalib.datatype.ArrayDatatype;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.nio.ByteBuffer;

/**
 * Represents an HDF5 array data structure.
 * <p>
 * The {@code HdfArray} class encapsulates a multidimensional array in an HDF5 file,
 * associating raw byte data with an {@link ArrayDatatype} that defines the array's
 * structure, dimensions, and base datatype. It implements the {@link HdfData} interface
 * to provide methods for accessing the data and converting it to various Java types.
 * </p>
 *
 * @see HdfData
 * @see ArrayDatatype
 */
public class HdfArray implements HdfData {
    /**
     * The raw byte array containing the array data.
     */
    private final byte[] bytes;
    /**
     * The ArrayDatatype defining the array's structure and format.
     */
    private final ArrayDatatype datatype;

    /**
     * Constructs an HdfArray from a byte array and a specified ArrayDatatype.
     * <p>
     * This constructor initializes the HdfArray by storing a reference to the provided
     * byte array and associating it with the given datatype. The byte array length must
     * match the size specified by the datatype, or an exception is thrown. The byte array
     * is expected to be formatted according to the datatype's specifications, including
     * any endianness and dimension ordering requirements.
     * </p>
     *
     * @param bytes    the byte array containing the array data
     * @param datatype the ArrayDatatype defining the array structure, dimensions, and base datatype
     * @throws IllegalArgumentException if the byte array length does not match the datatype's size
     * @throws NullPointerException     if either {@code bytes} or {@code datatype} is null
     */
    public HdfArray(byte[] bytes, ArrayDatatype datatype) {
        if (bytes == null || datatype == null) {
            throw new NullPointerException("Bytes and datatype must not be null");
        }
        if (bytes.length != datatype.getSize()) {
            throw new IllegalArgumentException(
                    String.format("Byte array length (%d) does not match datatype size (%d)",
                            bytes.length, datatype.getSize())
            );
        }
        this.bytes = bytes;
        this.datatype = datatype;
    }

    /**
     * Returns a copy of the byte array containing the array data.
     *
     * @return a cloned byte array to prevent external modification
     */
    public byte[] getBytes() {
        return bytes.clone();
    }

    /**
     * Returns a string representation of the array data.
     * <p>
     * The string representation is generated by delegating to the associated
     * {@code ArrayDatatype}, which formats the byte data according to its structure
     * and base datatype.
     * </p>
     *
     * @return a string representation of the array
     */
    @Override
    public String toString() {
        try {
            return datatype.getInstance(String.class, bytes);
        } catch (InvocationTargetException e) {
            throw new RuntimeException(e);
        } catch (InstantiationException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Writes the array data to the provided ByteBuffer.
     *
     * @param buffer the ByteBuffer to write the byte data to
     */
    @Override
    public void writeValueToByteBuffer(ByteBuffer buffer) {
        buffer.put(bytes);
    }

    /**
     * Converts the array data to an instance of the specified Java class.
     * <p>
     * This method delegates to the associated {@code ArrayDatatype} to perform
     * the conversion, allowing the data to be interpreted as the requested type
     * (e.g., multidimensional array, String, or other supported types).
     * </p>
     *
     * @param <T>   the type of the instance to be created
     * @param clazz the Class object representing the target type
     * @return an instance of type T created from the byte data
     * @throws UnsupportedOperationException if the datatype cannot convert to the requested type
     */
    @Override
    public <T> T getInstance(Class<T> clazz) throws IOException, InvocationTargetException, InstantiationException, IllegalAccessException {
        return datatype.getInstance(clazz, bytes);
    }
}