/**
 * A pure Java library for reading HDF5 files, providing support for datasets in the root group, including compound datasets,
 * scalars, vectors, and multi-dimensional datasets. It handles various datatypes such as fixed-point, floating-point, and strings,
 * and is compatible with HDF5 files generated by the C++ HDF5 library.
 *
 * <p>This package enables Java developers to access and manipulate HDF5 data without requiring external native libraries,
 * making it suitable for scientific computing, data analysis, and applications dealing with large hierarchical datasets.</p>
 *
 * <p>For detailed usage examples and reading capabilities, refer to the project documentation.</p>
 *
 * @since 0.1.3
 */
package org.hdf5javalib;